"use client";
import { useEffect,useMemo,useState } from "react";
import { BadgePercent,CheckCircle2,ShieldCheck } from "lucide-react";
import { calculatePromotionScenarios,PromotionInput,PromotionKind } from "../../lib/otaPromotionEngine";
import type { OtaRate } from "../properties/OtaRateProfileManager";
type Property={id:string;client_code:string;property_name:string};
const labels:Record<string,string>={mobile:"Mobile",country:"Country",getaway:"Getaway",early_year:"Early Year",basic:"Basic",last_minute:"Last-minute",early_booker:"Early Booker",limited_time:"Limited-time",genius:"Genius"};
export default function OtaPromotionsTool(){
 const[properties,setProperties]=useState<Property[]>([]),[rates,setRates]=useState<OtaRate[]>([]),[propertyId,setPropertyId]=useState(""),[rateId,setRateId]=useState(""),[enabled,setEnabled]=useState<Record<string,boolean>>({}),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/ota-promotions").then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error);setProperties(payload.properties||[]);setRates(payload.rates||[]);setPropertyId(payload.properties?.[0]?.id||"")}).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load OTA rates."))},[]);
 const propertyRates=useMemo(()=>rates.filter(rate=>rate.property_id===propertyId),[rates,propertyId]);useEffect(()=>{setRateId(propertyRates[0]?.id||"")},[propertyId,propertyRates]);
 const rate=rates.find(item=>item.id===rateId);
 const promotions=useMemo<PromotionInput[]>(()=>rate?[{kind:"genius",label:"Genius",percent:rate.genius_percent,enabled:enabled.genius??rate.genius_percent>0},{kind:rate.audience_kind as PromotionKind,label:labels[rate.audience_kind],percent:rate.audience_percent,enabled:enabled.audience??rate.audience_percent>0},{kind:rate.campaign_kind as PromotionKind,label:labels[rate.campaign_kind],percent:rate.campaign_percent,enabled:enabled.campaign??rate.campaign_percent>0},{kind:rate.deal_kind as PromotionKind,label:labels[rate.deal_kind],percent:rate.deal_percent,enabled:enabled.deal??rate.deal_percent>0},{kind:"limited_time",label:"Limited-time",percent:rate.limited_time_percent,enabled:enabled.limited??rate.limited_time_percent>0}]:[],[rate,enabled]);
 const scenarios=rate?calculatePromotionScenarios(Number(rate.rack_rate_usd),Number(rate.commission_percent),promotions):[],best=scenarios[0];const toggle=(key:string)=>setEnabled(current=>({...current,[key]:!current[key]}));
 return <section className="ota-simulator"><header><div><small>BOOKING.COM RATE LAB</small><h2>OTA Promotions Simulator</h2><p>See the lowest valid guest price and expected payout before activating promotions.</p></div><BadgePercent size={34}/></header>
 <div className="ota-simulator-setup"><label><span>1 · Choose hotel</span><select value={propertyId} onChange={event=>{setPropertyId(event.target.value);setEnabled({})}}>{properties.map(item=><option key={item.id} value={item.id}>{item.property_name} · {item.client_code}</option>)}</select></label><label><span>2 · Choose room and meal plan</span><select value={rateId} onChange={event=>{setRateId(event.target.value);setEnabled({})}}>{propertyRates.map(item=><option key={item.id} value={item.id}>{item.room_name} · {item.meal_plan}</option>)}</select></label></div>{error&&<p className="workspace-error">{error}</p>}
 {rate&&<><div className="ota-simulator-summary"><article><small>RACK RATE</small><strong>USD {Number(rate.rack_rate_usd).toFixed(2)}</strong><span>{rate.room_name} · {rate.meal_plan}</span></article><article className="guest"><small>LOWEST VALID GUEST PRICE</small><strong>USD {best?.guestPrice.toFixed(2)}</strong><span>{best?.effectiveDiscount.toFixed(1)}% effective discount</span></article><article className="payout"><small>ESTIMATED HOTEL PAYOUT</small><strong>USD {best?.hotelPayout.toFixed(2)}</strong><span>After {rate.commission_percent}% commission assumption</span></article></div>
 <section className="ota-promotion-switches"><header><div><small>3 · TEST ACTIVE PROMOTIONS</small><h3>Switch promotions on or off</h3></div><span><ShieldCheck size={16}/> Compatibility protected</span></header><div>{promotions.map((promotion,index)=>{const key=["genius","audience","campaign","deal","limited"][index];return <button key={key} className={promotion.enabled?"active":""} disabled={!promotion.percent} onClick={()=>toggle(key)}><i>{promotion.enabled?"✓":""}</i><span><strong>{promotion.label}</strong><small>{promotion.percent?`${promotion.percent}% discount`:"Not configured"}</small></span></button>})}</div></section>
 <section className="ota-winning-stack"><div><CheckCircle2/><span><small>WINNING VALID STACK</small><h3>{best?.promotions.length?best.promotions.map(item=>`${item.label} ${item.percent}%`).join(" + "):"Rack rate only"}</h3></span></div><p>Discounts are applied sequentially, not added together. Incompatible combinations are removed and no result uses more than three promotions.</p></section>
 <section className="ota-scenario-table"><header><h3>Valid price outcomes</h3><span>{scenarios.length} combinations checked</span></header>{scenarios.slice(0,8).map((scenario,index)=><div key={index}><span>{scenario.promotions.length?scenario.promotions.map(item=>item.label).join(" + "):"No promotion"}</span><strong>USD {scenario.guestPrice.toFixed(2)}</strong><small>{scenario.effectiveDiscount.toFixed(1)}% off</small><b>USD {scenario.hotelPayout.toFixed(2)} payout</b></div>)}</section><p className="ota-rule-note">Planning aid only. Booking.com eligibility, campaign dates and Partner Centre configuration remain authoritative.</p></>}
 {!rate&&!error&&<div className="workspace-empty"><strong>No OTA rates for this hotel</strong><p>Add them in Properties → OTA Rates.</p></div>}</section>
}
