export type HospitalityQuestionSeed = {
  slug: string;
  term: string;
  definition: string;
  category: string;
  difficulty: "Easy" | "Medium" | "Advanced";
};

const category = (
  name: string,
  rows: Array<[string, string, HospitalityQuestionSeed["difficulty"]?]>,
): HospitalityQuestionSeed[] => rows.map(([term, definition, difficulty = "Easy"]) => ({
  slug: `${name}-${term}`.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
  term,
  definition,
  category: name,
  difficulty,
}));

export const hospitalityQuestionBank: HospitalityQuestionSeed[] = [
  ...category("Reservations", [
    ["Reservation", "An arrangement made in advance to hold accommodation for a guest."],
    ["Confirmation number", "The unique reference used to identify a confirmed booking."],
    ["No-show", "A guest who has a reservation but does not arrive and has not cancelled."],
    ["Cancellation", "The formal removal of a reservation before the guest arrives."],
    ["Booking amendment", "A change made to an existing reservation, such as dates, guests or room type."],
    ["Guaranteed reservation", "A booking secured by payment details or a deposit and held according to its terms.", "Medium"],
    ["Tentative booking", "A provisional reservation that has not yet received final confirmation."],
    ["Overbooking", "Accepting more reservations than the available inventory based on expected cancellations or no-shows.", "Medium"],
    ["Waitlist", "A list of guests waiting for accommodation to become available."],
    ["Lead time", "The number of days between the booking date and the arrival date.", "Medium"],
    ["Length of stay", "The total number of nights included in a reservation."],
    ["Booking window", "The period between when a guest makes a booking and when the stay begins.", "Medium"],
  ]),
  ...category("Front Office", [
    ["Check-in", "The arrival process in which a guest is registered and given access to a room."],
    ["Check-out", "The departure process in which charges are settled and the guest leaves the property."],
    ["Registration card", "A document recording the guest’s identity, stay details and acknowledgement of hotel terms."],
    ["Walk-in guest", "A guest who requests accommodation without having made a prior reservation."],
    ["Guest folio", "The itemised financial account containing a guest’s room charges, payments and other transactions.", "Medium"],
    ["Wake-up call", "A scheduled telephone or automated alert requested by a guest."],
    ["Late check-out", "Permission for a guest to leave the room after the property’s standard departure time."],
    ["Early check-in", "Permission for a guest to access a room before the property’s standard arrival time."],
    ["Room assignment", "The process of allocating a specific room to a reservation."],
    ["Key card", "An encoded card or device used by a guest to unlock an assigned room."],
    ["Concierge", "A staff function that helps guests with local information, transport, bookings and special arrangements."],
    ["Night audit", "The end-of-day process that verifies transactions, balances accounts and closes the hotel business date.", "Advanced"],
  ]),
  ...category("Room Types", [
    ["Single room", "A room primarily arranged to accommodate one guest."],
    ["Double room", "A room normally furnished with one bed intended for two guests."],
    ["Twin room", "A room furnished with two separate beds."],
    ["Triple room", "A room configured to accommodate three guests."],
    ["Suite", "Accommodation with a larger layout and typically separate sleeping and living areas."],
    ["Connecting rooms", "Two rooms linked by a private internal door."],
    ["Adjoining rooms", "Rooms located next to or near one another without necessarily having an internal door."],
    ["Accessible room", "A room designed with features that support guests with mobility or other accessibility needs."],
    ["Sea-view room", "A room sold on the basis that it offers a view of the sea."],
    ["Family room", "A room configured to accommodate adults travelling with children."],
    ["Extra bed", "An additional temporary bed placed in a room for another occupant."],
    ["Maximum occupancy", "The highest number of guests permitted to stay in a particular room or room type.", "Medium"],
  ]),
  ...category("Meal Plans", [
    ["Room Only", "A rate that includes accommodation without any meals."],
    ["Bed and Breakfast", "A rate that includes accommodation and breakfast."],
    ["Half Board", "A rate that normally includes accommodation, breakfast and one main meal.", "Medium"],
    ["Full Board", "A rate that includes accommodation, breakfast, lunch and dinner.", "Medium"],
    ["All Inclusive", "A package covering accommodation, specified meals, drinks and selected services or activities.", "Medium"],
    ["Continental Plan", "A meal plan traditionally including the room and a continental breakfast.", "Medium"],
    ["European Plan", "A traditional term for a room rate that does not include meals.", "Medium"],
    ["Modified American Plan", "A traditional meal plan including the room, breakfast and either lunch or dinner.", "Advanced"],
    ["American Plan", "A traditional meal plan including the room and three daily meals.", "Advanced"],
    ["Breakfast buffet", "A self-service breakfast presentation offering a selection of dishes."],
    ["À la carte", "Food and beverages ordered as individually priced menu items."],
    ["Set menu", "A predetermined selection of courses offered for a fixed price."],
  ]),
  ...category("Housekeeping", [
    ["Occupied room", "A room currently registered to an in-house guest."],
    ["Vacant clean", "An unoccupied room that has been cleaned and is ready for inspection or sale."],
    ["Vacant dirty", "An unoccupied room that requires cleaning before it can be sold."],
    ["Out of order", "A room removed from sale because a serious fault or maintenance issue prevents use.", "Medium"],
    ["Turndown service", "An evening housekeeping service that prepares an occupied room for the night."],
    ["Linen", "Washable fabric items such as sheets, pillowcases, towels and tablecloths."],
    ["Guest amenities", "Complimentary in-room items supplied for guest comfort or convenience."],
    ["Do Not Disturb", "A guest instruction requesting that staff do not enter or contact the room."],
    ["Make Up Room", "A guest request asking housekeeping to clean and service the room."],
    ["Deep cleaning", "A detailed cleaning process beyond the normal daily room service routine."],
    ["Lost and found", "The controlled process for recording, storing and returning items left by guests."],
    ["Room discrepancy", "A difference between the room status reported by housekeeping and the status shown by front office.", "Advanced"],
  ]),
  ...category("Revenue Management", [
    ["Average Daily Rate", "Room revenue divided by the number of rooms sold for the same period.", "Medium"],
    ["Revenue per Available Room", "Room revenue divided by total available rooms, combining rate and occupancy performance.", "Advanced"],
    ["Occupancy percentage", "Rooms sold divided by rooms available, expressed as a percentage.", "Medium"],
    ["Yield management", "Adjusting availability and prices to maximise revenue from limited room inventory.", "Advanced"],
    ["Dynamic pricing", "Changing room prices in response to demand, timing, availability and market conditions.", "Medium"],
    ["Best Available Rate", "The best unrestricted publicly available rate offered by a hotel at a given time.", "Medium"],
    ["Rack rate", "The property’s standard published room price before discounts or negotiated offers."],
    ["FIT rate", "A rate intended for a free independent traveller rather than an organised group.", "Medium"],
    ["Group rate", "A negotiated price offered for a specified block of rooms used by a group."],
    ["Rate parity", "Keeping equivalent public room rates consistent across selected distribution channels.", "Advanced"],
    ["Closed to arrival", "A restriction that prevents a guest from starting a stay on a specified date.", "Advanced"],
    ["Minimum length of stay", "A restriction requiring a reservation to include at least a specified number of nights.", "Advanced"],
  ]),
  ...category("Distribution", [
    ["Online Travel Agency", "A website or application that markets and sells travel products from multiple suppliers."],
    ["Channel manager", "Software that synchronises room rates, availability and restrictions across sales channels.", "Medium"],
    ["Global Distribution System", "A network used by travel professionals to access and book travel inventory.", "Advanced"],
    ["Booking engine", "A direct online tool that lets guests check availability and reserve through the property’s own website."],
    ["Extranet", "A secure partner portal used to manage a property’s content, rates and reservations on a sales channel."],
    ["Room inventory", "The quantity of rooms available to sell for particular dates."],
    ["Allotment", "A specified number of rooms reserved for sale by a partner or channel.", "Medium"],
    ["Stop sell", "An instruction that closes a room or rate plan for new bookings on selected dates."],
    ["Room mapping", "Linking the correct hotel room types and rate plans between connected systems.", "Advanced"],
    ["Merchant model", "A sales model where the channel collects from the guest and later pays the property.", "Advanced"],
    ["Agency model", "A sales model where the property normally collects from the guest and pays commission to the channel.", "Advanced"],
    ["OTA commission", "The fee paid to an online travel agency for a reservation generated through its platform."],
  ]),
  ...category("Guest Service", [
    ["Service recovery", "Actions taken to resolve a failure and restore a dissatisfied guest’s confidence.", "Medium"],
    ["Upselling", "Encouraging a guest to purchase a higher-value version of the product they are considering."],
    ["Cross-selling", "Offering a related service or product in addition to the guest’s primary purchase."],
    ["Guest complaint", "An expression of dissatisfaction requiring acknowledgement, investigation and response."],
    ["Escalation", "Passing an unresolved or serious matter to someone with greater authority or expertise."],
    ["VIP guest", "A guest identified for special recognition or service based on status or importance."],
    ["Repeat guest", "A person who has stayed at the property on a previous occasion."],
    ["Special request", "A guest preference or requirement attached to a reservation but not always guaranteed."],
    ["Guest profile", "A record of a guest’s identity, contact details, history and useful preferences."],
    ["Guest feedback", "Comments or ratings provided by guests about their experience."],
    ["Courtesy call", "A proactive call made to check guest satisfaction or confirm that a request was resolved."],
    ["Personalisation", "Adapting service using known guest preferences and relevant stay information.", "Medium"],
  ]),
  ...category("Payments", [
    ["Pre-authorisation", "A temporary hold placed on available card funds without completing the final charge.", "Medium"],
    ["Deposit", "Money collected in advance to secure a booking or cover part of its value."],
    ["Advance payment", "Payment collected before the guest receives the accommodation or service."],
    ["Partial payment", "A payment covering only part of the total amount due."],
    ["Refund", "Money returned to a guest after a payment has already been collected."],
    ["Chargeback", "A card payment reversed through the cardholder’s bank following a dispute.", "Advanced"],
    ["Invoice", "A formal document listing goods or services supplied and the amount payable."],
    ["Receipt", "A document confirming that a payment has been received."],
    ["City ledger", "Accounts receivable records for approved companies or parties billed after guest departure.", "Advanced"],
    ["Cash float", "A fixed amount of cash kept at a payment point to provide change and begin operations."],
    ["Incidental charge", "An additional guest expense such as minibar, laundry, transport or room service."],
    ["Balance due", "The remaining amount that has not yet been paid."],
  ]),
  ...category("Sales and Marketing", [
    ["Sales lead", "A person or organisation that may become a customer."],
    ["Prospect", "A potential customer assessed as having a realistic interest or need."],
    ["Conversion", "The successful movement of an enquiry or visitor into a confirmed customer or booking."],
    ["Corporate rate", "A negotiated room price offered to an approved company."],
    ["Request for Proposal", "A formal invitation asking hotels to submit rates and service terms for business.", "Advanced"],
    ["MICE", "Meetings, incentives, conferences and exhibitions business.", "Advanced"],
    ["Direct booking", "A reservation made with the property without an external booking intermediary."],
    ["Marketing campaign", "A coordinated set of promotional activities designed to achieve a defined objective."],
    ["Target market", "The specific customer group a hotel aims to attract."],
    ["Hotel package", "A combined offer containing accommodation and one or more additional services or benefits."],
    ["Promotion code", "A code entered during booking to unlock a particular offer or rate."],
    ["Call to action", "A clear instruction encouraging the audience to take the next desired step."],
  ]),
  ...category("Safety and Security", [
    ["Evacuation", "The organised movement of guests and staff away from danger to a safer location."],
    ["Assembly point", "The designated safe place where people gather after evacuating a building."],
    ["Fire extinguisher", "A portable device used to control a small fire when it is safe and appropriate to do so."],
    ["Incident report", "A factual written record of an accident, security issue or unusual event."],
    ["First aid", "Immediate basic care provided until professional medical assistance is available."],
    ["Hazard", "A condition or object with the potential to cause harm."],
    ["Emergency exit", "A clearly marked route or door intended for use during an emergency."],
    ["Food allergy", "An immune reaction to a food that may require strict avoidance and urgent care."],
    ["Data privacy", "Protecting personal information and using it only for legitimate authorised purposes."],
    ["Key control", "Procedures for issuing, tracking, protecting and recovering room or master keys."],
    ["Suspicious package", "An unattended or unusual item that must not be touched and should be reported under security procedure."],
    ["Duty manager", "The manager responsible for operational decisions and escalation during a particular period."],
  ]),
  ...category("Hospitality English", [
    ["Sold out", "Having no remaining rooms available to sell for the requested period."],
    ["Complimentary", "Provided to the guest without an additional charge."],
    ["Availability", "The rooms, products or services that can still be booked for selected dates."],
    ["Arrival date", "The date on which the guest is expected to check in."],
    ["Departure date", "The date on which the guest is expected to check out."],
    ["Luggage storage", "Secure temporary holding of guest baggage before check-in or after check-out."],
    ["Reservation under a name", "A phrase used to identify the person whose name appears as the primary booking holder."],
    ["Subject to availability", "Not guaranteed and provided only if the requested item or service remains available."],
    ["Non-refundable rate", "A rate whose payment is normally retained if the guest cancels, subject to its stated terms.", "Medium"],
    ["Flexible rate", "A rate allowing cancellation or modification under more forgiving conditions than a restricted rate."],
    ["Estimated arrival time", "The approximate time at which the guest expects to reach the property."],
    ["In-house guest", "A registered guest who is currently staying at the property."],
  ]),
  ...advancedHospitalityQuestionBank,
];
import { advancedHospitalityQuestionBank } from "./hospitalityQuestionBankAdvanced";
