type Difficulty = "Easy" | "Medium" | "Advanced";

const subject = (
  category: string,
  rows: Array<[string, string, Difficulty?]>,
) => rows.map(([term, definition, difficulty = "Easy"]) => ({
  slug: `${category}-${term}`.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
  term,
  definition,
  category,
  difficulty,
}));

export const advancedHospitalityQuestionBank = [
  ...subject("Food and Beverage Service", [
    ["Mise en place", "Preparing and arranging all equipment, ingredients and service items before an operation begins.", "Medium"],
    ["Cover", "The complete place setting prepared for one guest at a dining table."],
    ["Table d’hôte", "A fixed-price menu offering a limited choice of complete courses.", "Medium"],
    ["Suggestive selling", "Recommending suitable additional items to improve the guest experience and increase value."],
    ["Sequence of service", "The agreed order of steps followed from welcoming a guest until completing the dining experience."],
    ["Silver service", "A formal style in which food is served to the guest from a platter using service utensils.", "Advanced"],
    ["Room service", "Food and beverage service delivered to a guest’s room."],
    ["Banquet service", "Food and beverage service organised for a pre-arranged group event."],
    ["Beverage pairing", "Selecting a drink that complements the flavours and style of a dish.", "Medium"],
    ["Order docket", "The recorded food and beverage order communicated to production and billing points."],
    ["Last order", "The final time by which guests may place an order before an outlet closes."],
    ["Service charge", "A stated amount added to a bill for service, subject to applicable policy and law."],
  ]),
  ...subject("Food Safety", [
    ["Cross-contamination", "The transfer of harmful microorganisms or allergens from one food, surface or item to another.", "Medium"],
    ["Temperature danger zone", "The temperature range in which harmful bacteria can multiply rapidly in food.", "Advanced"],
    ["FIFO", "Using stock with the earliest received or expiry date before newer stock."],
    ["Use-by date", "The safety date after which a highly perishable food should not be consumed."],
    ["Foodborne illness", "Sickness caused by consuming food or drink contaminated with harmful organisms or substances."],
    ["Allergen matrix", "A controlled reference showing which menu items contain specified food allergens.", "Medium"],
    ["Personal hygiene", "Practices such as handwashing and clean clothing that reduce contamination risk."],
    ["Sanitising", "Reducing microorganisms on a cleaned surface to an acceptable safe level."],
    ["Cold chain", "Keeping temperature-sensitive products continuously within their required chilled or frozen range.", "Medium"],
    ["HACCP", "A preventive system that identifies, evaluates and controls significant food-safety hazards.", "Advanced"],
    ["Probe thermometer", "A calibrated instrument used to measure the internal temperature of food."],
    ["Pest control", "Planned prevention, monitoring and treatment of insects, rodents and other pests."],
  ]),
  ...subject("Laundry Operations", [
    ["Par stock", "The standard quantity of linen required to support normal operations and replacement cycles.", "Medium"],
    ["Linen count", "The controlled physical count of linen issued, returned, stored or sent for washing."],
    ["Stain treatment", "Applying the correct process to remove a stain before normal washing."],
    ["Laundry sorting", "Separating items by fabric, colour, soil level and required washing method."],
    ["Wash formula", "The programmed combination of time, temperature, chemicals and mechanical action for a load.", "Advanced"],
    ["Linen discard", "Removing damaged or unsuitable linen from usable hotel stock under an approved process."],
    ["Guest laundry", "A paid service for washing, pressing or dry-cleaning a guest’s personal clothing."],
    ["Laundry manifest", "A record listing items transferred between the hotel and an internal or external laundry."],
    ["Flatwork", "Flat linen items such as sheets, pillowcases, napkins and tablecloths."],
    ["Terry linen", "Absorbent looped-fabric items such as bath towels, hand towels and bathmats."],
    ["Shrinkage", "A reduction in fabric dimensions caused by washing, drying, heat or unsuitable processing."],
    ["Rewash rate", "The proportion of laundry that must be processed again because it did not meet quality standards.", "Medium"],
  ]),
  ...subject("Engineering and Maintenance", [
    ["Preventive maintenance", "Planned inspection and servicing performed before equipment or facilities fail.", "Medium"],
    ["Corrective maintenance", "Repair work carried out after a fault or failure has been identified."],
    ["Work order", "A controlled request authorising and recording a maintenance task."],
    ["Out of service", "A room or facility temporarily unavailable for a limited operational reason.", "Medium"],
    ["Asset register", "A structured record of equipment and property assets, including identity and maintenance information."],
    ["Planned maintenance schedule", "A calendar showing when recurring inspections and servicing must be completed."],
    ["Energy meter", "A device used to measure consumption of electricity, water, gas or another utility."],
    ["Generator test", "A controlled operational check confirming that backup power equipment functions correctly."],
    ["Water pressure", "The force that moves water through pipes and affects guest and operational fixtures."],
    ["HVAC", "Systems used for heating, ventilation and air conditioning within a building.", "Medium"],
    ["Maintenance log", "A chronological record of reported faults, actions, parts and completion details."],
    ["Critical equipment", "Equipment whose failure could seriously affect safety, guests or essential hotel operations.", "Advanced"],
  ]),
  ...subject("Events and Banquets", [
    ["Banquet event order", "The detailed operational document describing an event’s timing, setup, menu and service requirements.", "Advanced"],
    ["Function sheet", "A shared event instruction summarising agreed arrangements for operational departments."],
    ["Guaranteed attendance", "The final confirmed guest number used for event preparation and billing terms.", "Medium"],
    ["Room setup", "The planned arrangement of furniture and equipment for an event."],
    ["Theatre style", "A meeting layout with rows of chairs facing a stage or presentation area."],
    ["Classroom style", "A meeting layout with tables and chairs facing the presenter."],
    ["U-shape setup", "Tables arranged in a U formation to support discussion and presentation."],
    ["Cocktail reception", "A standing event generally offering drinks and light food rather than seated dining."],
    ["Event deposit", "Advance payment collected to secure an event booking."],
    ["Audio-visual equipment", "Presentation and sound equipment such as projectors, screens, microphones and speakers."],
    ["Event run sheet", "A timed sequence of activities, responsibilities and cues for an event.", "Medium"],
    ["Post-event review", "A structured discussion of results, feedback and improvements after an event."],
  ]),
  ...subject("Purchasing and Inventory", [
    ["Purchase requisition", "An internal request seeking approval to obtain specified goods or services."],
    ["Purchase order", "An authorised document sent to a supplier confirming items, quantities, prices and terms."],
    ["Goods received note", "A record confirming the quantity and condition of goods delivered by a supplier."],
    ["Supplier quotation", "A supplier’s formal offer stating prices, availability and commercial terms."],
    ["Reorder level", "The stock quantity that triggers a new purchase before an item runs out.", "Medium"],
    ["Minimum stock level", "The lowest approved quantity that should be held to protect normal operations."],
    ["Maximum stock level", "The highest approved quantity held to avoid unnecessary cost, waste or storage pressure."],
    ["Stock variance", "The difference between the recorded stock quantity and the physical count."],
    ["Inventory turnover", "How frequently inventory is used and replaced during a period.", "Advanced"],
    ["Approved supplier", "A vendor assessed and authorised to provide particular goods or services."],
    ["Receiving inspection", "Checking delivered goods for quantity, quality, temperature, damage and specification."],
    ["Perpetual inventory", "A stock system updated continuously as items are received, issued or adjusted.", "Advanced"],
  ]),
  ...subject("Human Resources", [
    ["Job description", "A document defining a role’s purpose, duties, reporting relationship and requirements."],
    ["Induction", "The structured introduction of a new employee to the organisation, workplace and role."],
    ["Probation period", "An initial employment period used to assess suitability and performance under agreed terms."],
    ["Training needs analysis", "Identifying the knowledge and skills employees require to perform effectively.", "Medium"],
    ["Performance review", "A structured discussion of results, behaviour, development and future expectations."],
    ["Attendance record", "A controlled record of working time, absence, leave and punctuality."],
    ["Roster compliance", "Working according to the approved schedule and correctly recording authorised changes."],
    ["Grievance", "A formal workplace concern raised by an employee for fair review."],
    ["Disciplinary procedure", "A fair documented process for addressing alleged misconduct or serious performance concerns.", "Medium"],
    ["Employee engagement", "The level of commitment, involvement and positive connection employees feel toward their work."],
    ["Succession planning", "Preparing suitable employees to take on important future responsibilities.", "Advanced"],
    ["Confidentiality", "Protecting private employee, guest and business information from unauthorised disclosure."],
  ]),
  ...subject("Leadership and Supervision", [
    ["Delegation", "Assigning responsibility and appropriate authority while retaining accountability for the result."],
    ["Shift briefing", "A focused pre-shift meeting covering priorities, arrivals, risks and responsibilities."],
    ["Handover", "The structured transfer of important information and responsibility between employees or shifts."],
    ["Coaching", "Helping an employee improve through observation, questions, guidance and practice."],
    ["Constructive feedback", "Specific respectful information intended to reinforce strengths or improve behaviour."],
    ["Escalation path", "The agreed sequence for referring issues to the correct higher level of authority."],
    ["Span of control", "The number of employees or functions directly supervised by one manager.", "Advanced"],
    ["Root cause", "The underlying reason a problem occurred rather than only its visible symptom.", "Medium"],
    ["Corrective action", "A measured step taken to remove the cause of a detected problem and prevent recurrence."],
    ["Operational priority", "Work ranked as most important because of urgency, guest impact, safety or business need."],
    ["Accountability", "Accepting responsibility for decisions, actions and agreed outcomes."],
    ["Team recognition", "Timely acknowledgement of useful effort, improvement or achievement by employees."],
  ]),
  ...subject("Hotel Accounting", [
    ["Revenue", "Income earned from selling rooms, food, beverages and other hotel services."],
    ["Expense", "A cost incurred while operating the hotel or providing its services."],
    ["Profit", "The amount remaining when allowable expenses are deducted from revenue."],
    ["Accounts receivable", "Amounts owed to the hotel by approved guests, companies or other debtors."],
    ["Accounts payable", "Amounts the hotel owes to suppliers and other creditors."],
    ["Petty cash", "A controlled small cash fund used for approved minor expenses."],
    ["Cash reconciliation", "Comparing cash and payment records with actual funds and investigating differences."],
    ["Bank reconciliation", "Comparing internal cash records with a bank statement and resolving differences.", "Medium"],
    ["Accrual", "Recording income or expense in the period it is earned or incurred rather than when cash moves.", "Advanced"],
    ["Budget variance", "The difference between a budgeted amount and the actual result."],
    ["Cost centre", "A department or operational area for which costs are separately recorded and monitored."],
    ["Gross operating profit", "Hotel revenue remaining after deducting departmental and undistributed operating expenses.", "Advanced"],
  ]),
  ...subject("Digital Marketing", [
    ["Search engine optimisation", "Improving website content and structure to gain relevant visibility in unpaid search results.", "Medium"],
    ["Pay-per-click", "Online advertising in which the advertiser normally pays when a person clicks the advertisement."],
    ["Conversion rate", "The percentage of users who complete a desired action such as a booking or enquiry.", "Medium"],
    ["Landing page", "A focused web page designed to support a specific campaign or visitor action."],
    ["Content calendar", "A planned schedule of marketing topics, formats, channels and publishing dates."],
    ["Engagement rate", "A measure of audience interactions relative to reach, followers or impressions."],
    ["Remarketing", "Advertising again to people who previously interacted with a website or digital channel.", "Medium"],
    ["Organic reach", "The number of people who see content without paid distribution."],
    ["Brand voice", "The consistent personality and style used in an organisation’s communication."],
    ["User-generated content", "Photos, reviews or other content created by guests or customers rather than the hotel."],
    ["Reputation management", "Monitoring and improving how the property is represented in reviews and online discussion."],
    ["Direct booking strategy", "Coordinated actions designed to increase reservations through hotel-owned channels.", "Advanced"],
  ]),
  ...subject("Hotel Technology", [
    ["Property management system", "Core hotel software used to manage reservations, rooms, guests and front-office operations."],
    ["Point of sale", "A system used to record outlet sales, payments and related operational information."],
    ["Application programming interface", "A defined method allowing different software systems to exchange data.", "Advanced"],
    ["Two-factor authentication", "Account protection requiring two different forms of identity verification."],
    ["User permission", "A rule controlling which information or actions a system user may access."],
    ["Audit trail", "A chronological record showing important system actions, changes and responsible users."],
    ["Data backup", "A protected copy of information retained so it can be restored after loss or failure."],
    ["System integration", "Connecting technologies so that agreed information or processes move between them."],
    ["Webhook", "An automated message sent by one system to another when a specified event occurs.", "Advanced"],
    ["System downtime", "A period when technology is unavailable or unable to perform its intended function."],
    ["Phishing", "A deceptive attempt to obtain passwords or sensitive information by impersonating a trusted source."],
    ["Data synchronisation", "Keeping corresponding information consistent across connected systems.", "Medium"],
  ]),
  ...subject("Sustainability", [
    ["Energy conservation", "Reducing unnecessary energy use while maintaining safe and suitable hotel operations."],
    ["Water conservation", "Using water efficiently and preventing avoidable loss or waste."],
    ["Waste segregation", "Separating waste into defined categories to support safe handling, recycling or disposal."],
    ["Single-use plastic", "A plastic item designed to be used once before disposal or recycling."],
    ["Food waste", "Edible or inedible food material discarded during purchasing, preparation, service or consumption."],
    ["Responsible sourcing", "Purchasing with consideration for environmental, social and ethical impacts.", "Medium"],
    ["Carbon footprint", "The total greenhouse-gas emissions associated with an activity, organisation or product.", "Medium"],
    ["Green housekeeping", "Cleaning practices that reduce harmful chemicals, waste, water and energy use."],
    ["Linen reuse programme", "A guest-participation programme reducing unnecessary washing of towels or bed linen."],
    ["Local sourcing", "Purchasing suitable goods and services from nearby producers or suppliers."],
    ["Biodiversity", "The variety of living organisms and ecosystems that responsible operations seek to protect."],
    ["Sustainability audit", "A structured review of environmental and social performance against defined requirements.", "Advanced"],
  ]),
  ...subject("Quality Assurance", [
    ["Standard operating procedure", "An approved step-by-step instruction for completing a recurring task consistently."],
    ["Service standard", "A defined level or method of service employees are expected to deliver."],
    ["Quality inspection", "A structured check of rooms, facilities, products or service against agreed standards."],
    ["Checklist", "A controlled list used to confirm that required steps or conditions have been completed."],
    ["Non-conformance", "A result or condition that does not meet an agreed requirement or standard.", "Medium"],
    ["Mystery guest", "An evaluator who experiences hotel service anonymously and reports against defined criteria."],
    ["Guest satisfaction score", "A measured result summarising how positively guests rate their experience."],
    ["Continuous improvement", "Ongoing structured effort to make services, processes and results better over time."],
    ["Corrective action plan", "A documented set of responsibilities and deadlines for resolving identified problems."],
    ["Internal audit", "An objective review performed within the organisation to assess controls and compliance."],
    ["Benchmark", "A reference result or standard used to compare performance."],
    ["Quality culture", "Shared behaviour in which employees consistently value standards, learning and improvement.", "Advanced"],
  ]),
  ...subject("Spa and Wellness", [
    ["Treatment consultation", "A discussion used to understand a guest’s needs, suitability and relevant health information."],
    ["Contraindication", "A condition or circumstance that makes a treatment unsuitable or requires modification.", "Medium"],
    ["Treatment room turnaround", "Cleaning, sanitising and resetting a treatment room between guests."],
    ["Spa etiquette", "Expected guest and employee behaviour supporting privacy, calmness, hygiene and comfort."],
    ["Therapist allocation", "Assigning a suitably trained available therapist to a treatment booking."],
    ["Treatment duration", "The planned time allocated to deliver a particular spa service."],
    ["Wellness programme", "A structured set of activities or services supporting physical or mental wellbeing."],
    ["Spa retail", "Approved wellness or personal-care products offered for guest purchase."],
    ["Patch test", "A small controlled test used to check for sensitivity before applying a product more widely."],
    ["Relaxation area", "A quiet guest space intended for rest before or after a wellness treatment."],
    ["Treatment record", "A confidential record of the consultation, service delivered and relevant observations."],
    ["Spa occupancy", "The proportion of available treatment time or facilities used during a period.", "Medium"],
  ]),
  ...subject("Concierge and Transport", [
    ["Airport transfer", "Pre-arranged transport between an airport and the hotel or another agreed location."],
    ["Meet and greet", "A service in which a representative welcomes and assists an arriving guest."],
    ["Bell service", "Assistance with guest luggage, room escort and related arrival or departure needs."],
    ["Luggage tag", "An identification label used to control and trace baggage held or transported by the hotel."],
    ["Transport manifest", "A list of passengers, timings, destinations and assigned vehicles for a transfer."],
    ["Flight tracking", "Monitoring flight status to adjust an airport pickup or guest arrangement."],
    ["Local recommendation", "Relevant destination advice matched to a guest’s interests, timing and practical needs."],
    ["Restaurant reservation", "A confirmed dining arrangement made for a guest with an external or internal outlet."],
    ["Tour booking", "A confirmed guest arrangement for an excursion or guided experience."],
    ["Chauffeur service", "A pre-arranged vehicle service operated by a professional driver."],
    ["Guest escort", "Accompanying a guest to a room, facility, vehicle or destination while providing assistance."],
    ["Transport no-show", "A passenger who does not appear for a confirmed transfer within the agreed procedure."],
  ]),
];
