"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";

export type OtaRate={id:string;property_id:string|null;source_property_name:string;room_name:string;meal_plan:string;rack_rate_usd:number;commission_percent:number;genius_percent:number;audience_kind:string;audience_percent:number;campaign_kind:string;campaign_percent:number;deal_kind:string;deal_percent:number;limited_time_percent:number;needs_review:boolean;notes?:string|null};
async function request<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json"}});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Request failed.");return payload as T}

export default function OtaRateProfileManager({propertyId,propertyName,master}:{propertyId:string;propertyName:string;master:boolean}){
 const[rates,setRates]=useState<OtaRate[]>([]),[editing,setEditing]=useState<OtaRate|"new"|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{setRates((await request<{rates:OtaRate[]}>(`/api/ota-promotions?propertyId=${encodeURIComponent(propertyId)}`)).rates)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load OTA rates.")}},[propertyId]);
 useEffect(()=>{void load()},[load]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const values=Object.fromEntries(new FormData(event.currentTarget));await request("/api/ota-promotions",{method:editing==="new"?"POST":"PATCH",body:JSON.stringify({...values,property_id:propertyId,source_property_name:propertyName,...(editing!=="new"&&editing?{id:editing.id}:{})})});setEditing(null);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save OTA rate.")}finally{setBusy(false)}}
 return <section className="ota-profile-manager"><header><div><small>OTA RATE INVENTORY</small><h3>{rates.length} room and meal-plan rates</h3><p>Spreadsheet values remain editable. Review orange rows before commercial use.</p></div>{master&&<button className="primary-action" onClick={()=>setEditing("new")}>＋ Add OTA rate</button>}</header>{error&&<p className="workspace-error">{error}</p>}
 <div className="ota-profile-table"><div className="head"><span>Room / meal plan</span><span>Rack rate</span><span>Promotion setup</span><span/></div>{rates.map(rate=><button key={rate.id} className={rate.needs_review?"review":""} onClick={()=>master&&setEditing(rate)}><span><strong>{rate.room_name}</strong><small>{rate.meal_plan}</small></span><span><strong>USD {Number(rate.rack_rate_usd).toFixed(2)}</strong><small>{rate.commission_percent}% commission assumption</small></span><span><small>Genius {rate.genius_percent}% · {rate.audience_kind} {rate.audience_percent}%</small><small>{rate.campaign_kind} {rate.campaign_percent}% · {rate.deal_kind} {rate.deal_percent}% · Limited {rate.limited_time_percent}%</small></span><span>{rate.needs_review?"Review":master?"Edit":"View"}</span></button>)}</div>
 {!rates.length&&<div className="workspace-empty"><strong>No OTA rate profiles yet</strong><p>Add a room category and meal plan, or run the workbook migration.</p></div>}
 {editing&&<div className="calendar-detail-backdrop"><form className="ota-rate-form" onSubmit={save}><button type="button" className="modal-close" onClick={()=>setEditing(null)}>×</button><small>EDITABLE OTA PROFILE</small><h3>{editing==="new"?"Add room rate":editing.room_name}</h3><div className="ota-rate-fields">
 <label>Room category<input name="room_name" required defaultValue={editing==="new"?"":editing.room_name}/></label><label>Meal plan<input name="meal_plan" required defaultValue={editing==="new"?"Room Only":editing.meal_plan}/></label><label>Rack rate (USD)<input name="rack_rate_usd" type="number" min="0" step=".01" required defaultValue={editing==="new"?"":editing.rack_rate_usd}/></label><label>Commission assumption %<input name="commission_percent" type="number" min="0" max="100" step=".01" defaultValue={editing==="new"?15:editing.commission_percent}/></label>
 <label>Genius %<input name="genius_percent" type="number" min="0" max="100" defaultValue={editing==="new"?0:editing.genius_percent}/></label><label>Audience type<select name="audience_kind" defaultValue={editing==="new"?"mobile":editing.audience_kind}><option value="mobile">Mobile rate</option><option value="country">Country rate</option></select></label><label>Audience discount %<input name="audience_percent" type="number" min="0" max="100" defaultValue={editing==="new"?0:editing.audience_percent}/></label>
 <label>Campaign type<select name="campaign_kind" defaultValue={editing==="new"?"getaway":editing.campaign_kind}><option value="getaway">Getaway Deal</option><option value="early_year">Early Year Deal</option></select></label><label>Campaign discount %<input name="campaign_percent" type="number" min="0" max="100" defaultValue={editing==="new"?0:editing.campaign_percent}/></label><label>Standard deal<select name="deal_kind" defaultValue={editing==="new"?"basic":editing.deal_kind}><option value="basic">Basic Deal</option><option value="last_minute">Last-minute Deal</option><option value="early_booker">Early Booker</option></select></label><label>Standard deal %<input name="deal_percent" type="number" min="0" max="100" defaultValue={editing==="new"?0:editing.deal_percent}/></label><label>Limited-time %<input name="limited_time_percent" type="number" min="0" max="100" defaultValue={editing==="new"?0:editing.limited_time_percent}/></label><label className="wide">Notes<textarea name="notes" defaultValue={editing==="new"?"":editing.notes||""}/></label>
 </div><footer><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary-action" disabled={busy}>{busy?"Saving…":"Save OTA profile"}</button></footer></form></div>}</section>
}
