"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import ContactManager from "../contacts/ContactManager";

function title(item: any) { return item?.contact?.property_name || item?.contact?.contact_name || item?.contact?.profile_name || item?.contact?.phone || "WhatsApp contact"; }
function time(value?: string) { if (!value) return ""; const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : date.toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }); }

export default function WhatsAppInbox({ onCreate, staff }: { onCreate: () => void; staff: any }) {
  const master = String(staff?.access || "").toLowerCase() === "master";
  const [conversations, setConversations] = useState<any[]>([]), [team, setTeam] = useState<any[]>([]), [activeId, setActiveId] = useState(""), [messages, setMessages] = useState<any[]>([]), [notes, setNotes] = useState<any[]>([]);
  const [search, setSearch] = useState(""), [filter, setFilter] = useState("All"), [draft, setDraft] = useState(""), [note, setNote] = useState(""), [busy, setBusy] = useState(""), [error, setError] = useState(""), [contactsOpen, setContactsOpen] = useState<string | null>(null);
  const [mobileListMode, setMobileListMode] = useState(true);
  const messagesRef = useRef<HTMLDivElement>(null);
  const active = conversations.find(item => item.id === activeId) || null;
  const loadConversations = useCallback(async () => { try { const response = await fetch("/api/whatsapp/inbox", { cache: "no-store" }), data = await response.json(); if (!response.ok) throw new Error(data.error); setConversations(data.conversations || []); setTeam(data.staff || []); setActiveId(current => current || data.conversations?.[0]?.id || ""); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load inbox."); } }, []);
  const loadThread = useCallback(async (id: string) => { if (!id) return; try { const response = await fetch(`/api/whatsapp/inbox?conversation_id=${encodeURIComponent(id)}`, { cache: "no-store" }), data = await response.json(); if (!response.ok) throw new Error(data.error); setMessages(data.messages || []); setNotes(data.notes || []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load messages."); } }, []);
  useEffect(() => { void loadConversations(); const timer = window.setInterval(loadConversations, 7000); return () => window.clearInterval(timer); }, [loadConversations]);
  useEffect(() => { if (!activeId) return; void loadThread(activeId); const timer = window.setInterval(() => loadThread(activeId), 5000); return () => window.clearInterval(timer); }, [activeId, loadThread]);
  useEffect(() => {
    const container = messagesRef.current;
    if (!container) return;
    window.requestAnimationFrame(() => {
      container.scrollTo({ top: container.scrollHeight, behavior: "smooth" });
    });
  }, [activeId, messages.length]);
  const visible = useMemo(() => conversations.filter(item => `${title(item)} ${item.contact?.contact_name || ""} ${item.contact?.phone || ""}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All" || item.status === filter)), [conversations, search, filter]);
  async function update(patch: any) { if (!active) return; setConversations(rows => rows.map(row => row.id === active.id ? { ...row, ...patch } : row)); const response = await fetch("/api/whatsapp/inbox", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: active.id, ...patch }) }); const data = await response.json(); if (!response.ok) setError(data.error || "Update failed."); }
  async function select(id: string) { setActiveId(id); setMobileListMode(false); const item = conversations.find(row => row.id === id); if (item?.unread_count) await updateFor(id, { unread_count: 0 }); }
  async function updateFor(id: string, patch: any) { setConversations(rows => rows.map(row => row.id === id ? { ...row, ...patch } : row)); await fetch("/api/whatsapp/inbox", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, ...patch }) }); }
  async function send(event: FormEvent) { event.preventDefault(); if (!active || !draft.trim()) return; try { setBusy("send"); setError(""); const response = await fetch("/api/whatsapp/send", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ conversation_id: active.id, text: draft }) }), data = await response.json(); if (!response.ok) throw new Error(data.error); setDraft(""); await Promise.all([loadThread(active.id), loadConversations()]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Message failed."); } finally { setBusy(""); } }
  async function saveNote() { if (!active || !note.trim()) return; try { setBusy("note"); const response = await fetch("/api/whatsapp/inbox", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ conversation_id: active.id, note }) }), data = await response.json(); if (!response.ok) throw new Error(data.error); setNote(""); await loadThread(active.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Note failed."); } finally { setBusy(""); } }
  async function removeConversation() { if (!master || !active || !window.confirm(`Permanently delete ${title(active)} and all its messages?`)) return; const response = await fetch(`/api/whatsapp/inbox?id=${encodeURIComponent(active.id)}`, { method: "DELETE" }), data = await response.json(); if (!response.ok) return setError(data.error || "Deletion failed."); setActiveId(""); setMessages([]); await loadConversations(); }
  return <div className="wa-workspace">
    <div className="wa-toolbar"><div><small>LIVE CLIENT COMMUNICATION</small><h2>WhatsApp Inbox</h2></div><div><span className="wa-connected"><i/> Connected</span><button onClick={() => setContactsOpen("")}>Manage contacts</button><button className="primary-action" onClick={onCreate}>＋ Create Task</button></div></div>
    {error && <div className="workspace-error">{error}</div>}
    <div className={`wa-grid ${mobileListMode ? "wa-mobile-list-mode" : "wa-mobile-chat-mode"}`}><section className="wa-list"><div className="wa-search"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search properties or contacts"/></div><div className="wa-filters">{["All","Open","Waiting","Follow-up","Closed"].map(x => <button className={filter === x ? "active" : ""} onClick={() => setFilter(x)} key={x}>{x}</button>)}</div><div className="wa-scroll">{visible.map(item => <button className={activeId === item.id ? "active" : ""} onClick={() => select(item.id)} key={item.id}><span className="wa-avatar">{title(item).slice(0,2).toUpperCase()}</span><div><strong>{title(item)}</strong><small>{item.contact?.contact_name || item.contact?.phone || "Unknown contact"}</small><p>{item.last_message_preview || "New conversation"}</p></div><time>{time(item.last_message_at)}</time>{item.unread_count > 0 && <b>{item.unread_count}</b>}</button>)}{visible.length === 0 && <div className="wa-empty">No matching conversations</div>}</div></section>
      <section className="wa-chat">{!active ? <div className="wa-empty-chat"><span>WA</span><strong>Select a conversation</strong><p>Messages and replies will appear here.</p></div> : <><header><button type="button" className="wa-mobile-back" onClick={() => setMobileListMode(true)} aria-label="Back to WhatsApp inbox">←</button><span className="wa-avatar large">{title(active).slice(0,2).toUpperCase()}</span><div><h3>{title(active)}</h3><p>{active.contact?.contact_name || "Unknown contact"} · {active.contact?.phone || ""}</p></div></header><div className="wa-messages" ref={messagesRef}>{messages.map(message => <div className={`wa-message ${message.direction === "outgoing" ? "out" : "in"}`} key={message.id}>{message.sent_by && <small>{message.sent_by}</small>}<p>{message.body || `[${message.message_type}]`}</p><time>{time(message.meta_timestamp || message.created_at)} {message.direction === "outgoing" ? message.delivery_status === "read" ? "✓✓" : "✓" : ""}</time></div>)}</div><form className="wa-compose" onSubmit={send}><small>{active.customer_window_expires_at && new Date(active.customer_window_expires_at) > new Date() ? "Customer reply window open" : "An approved template may be required"}</small><div><textarea value={draft} onChange={e => setDraft(e.target.value)} placeholder="Type a WhatsApp reply…"/><button disabled={busy === "send"}>{busy === "send" ? "…" : "Send"}</button></div></form></>}</section>
      <aside className="wa-details">{active && <><div className="wa-client"><span className="wa-avatar xl">{title(active).slice(0,2).toUpperCase()}</span><strong>{active.contact?.contact_name || active.contact?.profile_name || "WhatsApp contact"}</strong><p>{active.contact?.property_name || "Property not linked"}</p>{active.contact?.id && <button type="button" onClick={() => setContactsOpen(active.contact.id)}>Edit contact</button>}</div><label>Status<select value={active.status || "Open"} onChange={e => update({ status: e.target.value })}><option>Open</option><option>Waiting</option><option>Follow-up</option><option>Closed</option></select></label><label>Assigned to<select value={active.assigned_to || ""} onChange={e => update({ assigned_to: e.target.value || null })}><option value="">Unassigned</option>{team.map((item:any) => <option key={item.display_name}>{item.display_name}</option>)}</select></label><div className="wa-note"><strong>Internal notes</strong>{notes.slice(0,3).map(item => <p key={item.id}>{item.note}<small>{item.created_by} · {time(item.created_at)}</small></p>)}<textarea value={note} onChange={e => setNote(e.target.value)} placeholder="Private note for the team"/><button disabled={busy === "note" || !note.trim()} onClick={saveNote}>{busy === "note" ? "Saving…" : "Save note"}</button></div>{master && <div className="wa-danger-zone"><small>MASTER ACTION</small><button className="wa-delete" onClick={removeConversation}>Delete conversation</button></div>}</>}</aside></div>
    {contactsOpen !== null && (
      <ContactManager master={master} initialContactId={contactsOpen || undefined} onClose={() => setContactsOpen(null)} onChanged={loadConversations}/>
    )}
  </div>;
}
